# INITIAL DATA INSPECTATION AND QUALITY ASSESMENT

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("messydata.xlsx")

In [3]:
df

,employee_id,full_name,source_dataset,age,gender,ethnicity,education_level,years_experience,tenure_years,department,job_title,country,remote_status,performance_rating,performance_review_score,hire_date,currency,salary_raw,pay_band
0,E145770,Kenneth Alexander,survey_response_2024,43.0,Female,Black or African American,Associate Degree,25.0,0.0,Finance,Controller,Germany,Hybrid,Meets Expectations,3.6,2026-05-12 00:00:00,EUR,"���41,185",Band 2
1,E181146,Cory Warner,survey_response_2024,37.0,Female,White,PhD.,18.0,1.0,Sales,Sales Manager,India,remote,Meets Expectations,4.0,2026-05-13 00:00:00,INR,"4,715,450 INR",Band 3
2,E155936,April Leon,hris_export_2023,39.0,Man,Black or African American,High School,15.0,5.0,Marketing,Marketing Manager,Germany,Remote,Meets Expectations,NaN,2026-05-14 00:00:00,EUR,61833.17,Band 3
3,E133644,Jamie Garcia,hris_export_2023,38.0,Man,White,Master's,19.0,0.0,Marketing,SEO Specialist,Singapore,On-site,Meets Expectations,4.8,2026-05-15 00:00:00,SGD,41219.59,Band 1
4,E192474,Jamie Robinson,survey_response_2024,30.0,female,NaN,PhD.,10.0,7.0,Operations,Logistics Coordinator,Nigeria,REMOTE,Below Expectations,4.2,2026-05-16 00:00:00,NGN,"55,659,714 NGN",Band 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96895,LEG-6265,Melissa Smith,acquired_company_legacy,42.0,Female,White,BSc,19.0,6.0,Operations,Operations Analyst,Nigeria,hybrid,Exceeds Expectations,3.8,2291-08-26 00:00:00,NGN,44376433,Band 2
96896,LEG-54886,Jason Wong,acquired_company_legacy,39.0,Prefer not to say,NaN,MSc,19.0,6.0,Operations,Logistics Coordinator,Nigeria,REMOTE,Meets Expectations,3.0,2291-08-27 00:00:00,NGN,43033958,Band 1
96897,LEG-76820,Whitney Rose,acquired_company_legacy,39.0,Man,Pacific Islander,MSc,21.0,4.0,IT,Systems Administrator,Singapore,On site,exceeds,5.0,2291-08-28 00:00:00,SGD,69263,Band 2
96898,LEG-860,Vanessa Hatfield,acquired_company_legacy,35.0,male,White,MSc,15.0,2.0,Product,VP Product,Kenya,Remote,Exceeds Expectations,3.1,2291-08-29 00:00:00,KES,10490367,Band 3
96899,LEG-15795,Dennis Powell,acquired_company_legacy,39.0,F,Black or African American,Master's,17.0,0.0,Data Science,Data Scientist,India,NaN,Meets Expectations,3.3,2291-08-30 00:00:00,INR,4587608,Band 2

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
df.info()

Rows: 96900
Columns: 19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96900 entries, 0 to 96899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               96900 non-null  object
 1   full_name                 96900 non-null  object
 2   source_dataset            96900 non-null  object
 3   age                       93943 non-null  float64
 4   gender                    93974 non-null  object
 5   ethnicity                 72614 non-null  object
 6   education_level           92148 non-null  object
 7   years_experience          95931 non-null  float64
 8   tenure_years              95931 non-null  float64
 9   department                96900 non-null  object
 10  job_title                 96900 non-null  object
 11  country                   96900 non-null  object
 12  remote_status             86089 non-null  object
 13  performance_rating        92097 non-null  object
 14  performance_review_score  81824 non-null  float64
 15  hire_date                 96900 non-null  object
 16  currency                  96900 non-null  object
 17  salary_raw                96900 non-null  object
 18  pay_band                  96900 non-null  object
dtypes: float64(4), object(15)
memory usage: 14.0+ MB

In [5]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Null_Count": df.isnull().sum().values,
    "Null-percentage": (df.isnull().sum().values/len(df)*100).round(2),
    "Unique_Values": df.nunique().values})
quality_report

,Column,Data_Type,Null_Count,Null-percentage,Unique_Values
0,employee_id,object,0,0.00,96900
1,full_name,object,0,0.00,68153
2,source_dataset,object,0,0.00,3
3,age,float64,2957,3.05,49
4,gender,object,2926,3.02,15
5,ethnicity,object,24286,25.06,8
6,education_level,object,4752,4.90,10
7,years_experience,float64,969,1.00,41
8,tenure_years,float64,969,1.00,17
9,department,object,0,0.00,24
10,job_title,object,0,0.00,106
11,country,object,0,0.00,17
12,remote_status,object,10811,11.16,8
13,performance_rating,object,4803,4.96,5
14,performance_review_score,float64,15076,15.56,41
15,hire_date,object,0,0.00,96900
16,currency,object,0,0.00,12
17,salary_raw,object,0,0.00,92515
18,pay_band,object,0,0.00,5

In [6]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [7]:
df.select_dtypes(include=np.number).describe().T

,count,mean,std,min,25%,50%,75%,max
age,93943.0,35.602408,8.657487,20.0,29.0,35.0,42.0,68.0
years_experience,95931.0,14.670576,8.704923,0.0,8.0,14.0,21.0,40.0
tenure_years,95931.0,2.915648,2.549772,0.0,1.0,3.0,5.0,16.0
performance_review_score,81824.0,3.389828,0.867168,1.0,2.8,3.4,4.0,5.0

In [8]:
for column in df.select_dtypes(include="object").columns:
  print("\n", column)
  print(df[column].value_counts(dropna=False).head(20))

 employee_id
employee_id
LEG-15795    1
E145770      1
E181146      1
E155936      1
LEG-62955    1
E164925      1
E167969      1
E105311      1
E183104      1
E153707      1
E185305      1
LEG-28693    1
E171932      1
E193016      1
E125658      1
E184478      1
E118431      1
LEG-2747     1
E159150      1
LEG-65725    1
Name: count, dtype: int64

 full_name
full_name
Michael Smith        52
Michael Brown        32
John Smith           32
David Williams       31
James Smith          30
Michael Johnson      28
Michael Rodriguez    27
James Johnson        27
Jennifer Smith       27
Michael Jones        27
Robert Smith         27
Christopher Smith    26
Michael Anderson     26
Robert Johnson       25
David Johnson        25
Daniel Smith         24
Michael Williams     24
John Johnson         24
Amanda Smith         23
Thomas Smith         23
Name: count, dtype: int64

 source_dataset
source_dataset
hris_export_2023           48653
survey_response_2024       33636
acquired_company_legacy    14611
Name: count, dtype: int64

 gender
gender
MALE                 9917
male                 9847
Male                 9754
Man                  9685
M                    9643
FEMALE               8340
Woman                8286
female               8249
Female               8230
F                    8222
NaN                  2926
Prefer not to say     781
Other                 773
non-binary            765
NB                    758
Non-binary            724
Name: count, dtype: int64

 ethnicity
ethnicity
White                        32679
NaN                          24286
Asian                        11002
Black or African American     9343
Hispanic or Latino            9290
Two or More Races             4394
Native American               2230
Prefer not to say             2196
Pacific Islander              1480
Name: count, dtype: int64

 education_level
education_level
bachelor's degree    9369
PhD                  9368
Master's             9275
High School          9241
PhD.                 9232
BSc                  9213
MSc                  9196
Bachelors            9160
Bachelor's           9050
Associate Degree     9044
NaN                  4752
Name: count, dtype: int64

 department
department
HR                  8137
IT                  8085
Operations          8082
Finance             8035
Marketing           8009
Customer Support    8005
Design              8003
Engineering         7987
Sales               7938
Legal               7913
Product             7876
Data Science        7868
product               99
it                    91
legal                 89
marketing             83
engineering           83
hr                    81
sales                 79
design                78
Name: count, dtype: int64

 job_title
job_title
IT Manager                  2742
Systems Administrator       2667
Customer Success Manager    2653
General Counsel             2624
Support Team Lead           2604
Support Agent               2598
Paralegal                   2577
Legal Counsel               2553
IT Support Specialist       2506
Logistics Coordinator       2005
VP Design                   1999
Design Lead                 1966
UX Designer                 1964
COO                         1963
Operations Analyst          1960
Operations Manager          1960
Product Manager             1955
Product Analyst             1943
VP Product                  1927
Senior Product Manager      1914
Name: count, dtype: int64

 country
country
Kenya             5833
Germany           5820
South Africa      5785
Philippines       5760
US                5747
UK                5736
India             5726
Australia         5723
Canada            5687
United Kingdom    5685
Brazil            5666
USA               5664
Singapore         5646
United States     5635
Nigeria           5613
Netherlands       5595
France            5579
Name: count, dtype: int64

 remote_status
remote_status
Onsite     10925
remote     10872
Hybrid     10822
NaN        10811
On-site    10811
REMOTE     10715
Remote     10705
hybrid     10674
On site    10565
Name: count, dtype: int64

 performance_rating
performance_rating
Meets Expectations      43497
Exceeds Expectations    21430
meets                    9694
exceeds                  9692
Below Expectations       7784
NaN                      4803
Name: count, dtype: int64

 hire_date
hire_date
2291-08-30 00:00:00    1
2026-05-12 00:00:00    1
2026-05-13 00:00:00    1
2026-05-14 00:00:00    1
2291-08-14 00:00:00    1
2291-08-13 00:00:00    1
2291-08-12 00:00:00    1
2291-08-11 00:00:00    1
2291-08-10 00:00:00    1
2291-08-09 00:00:00    1
2291-08-08 00:00:00    1
2291-08-07 00:00:00    1
2291-08-06 00:00:00    1
2291-08-05 00:00:00    1
2291-08-04 00:00:00    1
2291-08-03 00:00:00    1
2291-08-02 00:00:00    1
2291-08-01 00:00:00    1
2291-07-31 00:00:00    1
2291-07-30 00:00:00    1
Name: count, dtype: int64

 currency
currency
USD    17046
EUR    16994
GBP    11421
KES     5833
ZAR     5785
PHP     5760
INR     5726
AUD     5723
CAD     5687
BRL     5666
SGD     5646
NGN     5613
Name: count, dtype: int64

 salary_raw
salary_raw
36037        5
30131        5
43623        5
43572        4
41349        4
30684        4
���45,358    4
36043        4
26437        4
27310        4
32113        4
31946        4
���43,574    4
28707        4
30165        4
30848        4
33573        4
35947        4
41957        4
32357        4
Name: count, dtype: int64

 pay_band
pay_band
Band 2    38449
Band 1    37584
Band 3    19115
Band 4     1737
Band 5       15
Name: count, dtype: int64

# DATA CLEANING

MISSING DATA TREATMENT

In [48]:
numeric_columns = df.select_dtypes(include=np.number).columns

In [10]:
df[numeric_columns].skew()

age                         0.205651
years_experience            0.248792
tenure_years                0.671289
performance_review_score   -0.165679
dtype: float64

In [64]:
df['age'] = df['age'].fillna(df['age'].mean())
df['tenure_years'] = df['tenure_years'].fillna(df['tenure_years'].mean())
df['years_experience'] = df['years_experience'].fillna(df['years_experience'].mean())
df['performance_review_score'] = df['performance_review_score'].fillna(df['performance_review_score'].median())

In [65]:
df['gender'] = df['gender'].fillna(df['gender'].mode()[0])
df['education_level'] = df['education_level'].fillna(df['education_level'].mode()[0])
df['remote_status'] = df['remote_status'].fillna(df['remote_status'].mode()[0])
df['performance_rating'] = df['performance_rating'].fillna(df['performance_rating'].mode()[0])
df['ethnicity'] = df['ethnicity'].fillna('unknown')

JUSTIFICATION:-

Different imputation strategies were applied based on the data type,distribution,and amount of missing data in each column. such that, in;


* Numerical columns such as Age, Tenure year, years of experience and Performance Review Score: Mean imputation was used because these variables were not highly skewed, making the mean the reasonable representation of the typical value with the exception of Performance review Score which median was used because it was highly skewed, and the median is less affected by extreme values and therefore provide more reliable replacement for the missing observation.

* Categories columnms such as Gender, Educational Level, Remote status, and Performance Rating: Mode imputation was used because these variables are categorical, and the most frequently occuring category provides a simple and appropriate replacement for the relatively small number of missing values

* For ethnicity ; Missing values were replaced with "Unknown" because the column contain a relatively large number of missing observations. Rather than asssigning these missing records to a particular ethnic group without evidence,"Unknown"preserves the original uncertainty and avoiding introducing bias into analysis.

STANDARDIZATION OF INCOSISTENT FORMATTING

In [13]:
df['gender'] = df['gender'].replace({
    'Man': 'Male',
    'M': 'Male',
    'Woman': 'Female',
    'F': 'Female',
    'NB': 'Non-Binary'

})

In [14]:
df['gender'] = df['gender'].str.title()
df['gender'] = df['gender'].str.strip()

In [15]:
df['education_level'] = df['education_level'].replace({
    "bachelor's degree": "Bachelor's",
    "Bachelors'": "Bachelor's",
    'Bachelors': "Bachelor's",
    'BSc': "Bachelor's",
    'MSc': "Master's",
    'PhD.': 'PhD',
    "Master'S": "Master's",
    "Bachelor'S": "Bachelor's"
})

In [16]:
df['education_level'] = df['education_level'].str.title()
df['education_level'] = df['education_level'].str.strip()

In [17]:
df['department'] = df['department'].str.title()
df['department'] = df['department'].str.strip()

In [18]:
df['remote_status'] = df['remote_status'].replace({
    'On site': 'Onsite',
    'On-site': 'Onsite',
    'Meets Expectational': 'Meets',
    'Exceeds Expectations': 'Exceeds'
})

In [19]:
df['remote_status'] = df['remote_status'].str.title()
df['remote_status'] = df['remote_status'].str.strip()

DATA TYPE CORRECTION

In [20]:
df['employee_id'] = df['employee_id'].astype('string')

In [45]:
df['hire_date'] = df['hire_date'].astype(str)

In [42]:
df['salary_raw'] = df['salary_raw'].str.replace(r'[^\d.-]', '', regex=True).astype(float)

In [59]:
df['salary_raw'] = pd.to_numeric(df['salary_raw'], errors='coerce')
df['salary_raw'] = df['salary_raw'].fillna(df['salary_raw'].median())

OUTLIER DETECTION

In [52]:
for col in numeric_columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
  print(f"{col}:{len(outliers)} outliers")

age:180 outliers
years_experience:0 outliers
tenure_years:149 outliers
performance_review_score:0 outliers
salary_raw:3271 outliers

In [53]:
for col in numeric_columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)][col]
  print(f"\n{col}")
  print(outliers.tolist())

age
[64.0, 63.0, 62.0, 62.0, 64.0, 68.0, 63.0, 62.0, 63.0, 62.0, 62.0, 63.0, 62.0, 66.0, 68.0, 63.0, 64.0, 63.0, 63.0, 68.0, 68.0, 65.0, 62.0, 67.0, 63.0, 64.0, 62.0, 64.0, 66.0, 63.0, 63.0, 62.0, 62.0, 62.0, 63.0, 63.0, 63.0, 67.0, 63.0, 65.0, 67.0, 66.0, 62.0, 67.0, 64.0, 66.0, 67.0, 63.0, 62.0, 62.0, 65.0, 68.0, 62.0, 63.0, 62.0, 64.0, 64.0, 65.0, 67.0, 64.0, 62.0, 64.0, 63.0, 66.0, 63.0, 67.0, 64.0, 63.0, 63.0, 62.0, 62.0, 64.0, 67.0, 62.0, 62.0, 62.0, 68.0, 63.0, 64.0, 68.0, 63.0, 62.0, 62.0, 65.0, 62.0, 62.0, 62.0, 62.0, 62.0, 64.0, 63.0, 68.0, 65.0, 68.0, 65.0, 64.0, 68.0, 63.0, 62.0, 67.0, 62.0, 63.0, 66.0, 63.0, 67.0, 63.0, 62.0, 63.0, 62.0, 63.0, 62.0, 62.0, 62.0, 66.0, 63.0, 63.0, 65.0, 67.0, 62.0, 65.0, 63.0, 62.0, 68.0, 67.0, 63.0, 63.0, 65.0, 62.0, 62.0, 62.0, 62.0, 64.0, 68.0, 67.0, 63.0, 64.0, 62.0, 66.0, 66.0, 64.0, 66.0, 66.0, 65.0, 62.0, 62.0, 62.0, 63.0, 64.0, 62.0, 63.0, 67.0, 63.0, 63.0, 62.0, 65.0, 65.0, 63.0, 63.0, 63.0, 62.0, 64.0, 64.0, 62.0, 63.0, 62.0, 62.0, 65.0, 67.0, 63.0, 62.0, 67.0, 65.0, 65.0, 62.0, 67.0, 67.0, 66.0, 62.0, 63.0, 67.0]

years_experience
[]

tenure_years
[12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 13.0, 13.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 15.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 14.0, 12.0, 12.0, 12.0, 12.0, 12.0, 16.0, 12.0, 12.0, 13.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 14.0, 12.0, 13.0, 12.0, 12.0, 14.0, 13.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 14.0, 12.0, 12.0, 12.0, 13.0, 12.0, 13.0, 12.0, 14.0, 12.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 13.0, 12.0, 12.0, 14.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 13.0, 13.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0, 14.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 13.0, 13.0, 14.0, 13.0, 12.0, 12.0, 12.0, 14.0, 12.0, 14.0, 13.0, 13.0, 12.0, 12.0, 13.0, 12.0, 12.0, 12.0, 12.0]

performance_review_score
[]

salary_raw

The IQR method were used to identify potential outliers in the numerical variables. The detected outlier in age, tenure years, salary were retained because the value were considered to be realistic and potentially meaningful observations rather than data-entry errors. Therefore, no capping or removal was performed.

# BEFORE VS AFTER SUMMARY TABLE

In [60]:
df.to_csv("cleaned_dataset.csv", index=False)

In [61]:
df_before = pd.read_excel("messydata.xlsx")

In [62]:
print("Before cleaning:", df_before.shape)
print("After cleaning:", df.shape)

Before cleaning: (96900, 19)
After cleaning: (96900, 19)

In [66]:
summary = pd.DataFrame({
    "Metric": [
        "Number of Rows",
        "Number of Columns",
        "Missing Values",
        "Duplicate Rows",
        "Numerical Columns",
        "Categorical Columns"
    ],
    "Before Cleaning": [
        df_before.shape[0],
        df_before.shape[1],
        df_before.isnull().sum().sum(),
        df_before.duplicated().sum(),
        len(df_before.select_dtypes(include=np.number).columns),
        len(df_before.select_dtypes(include="object").columns)
    ],
    "After Cleaning": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        len(df.select_dtypes(include=np.number).columns),
        len(df.select_dtypes(include="object").columns)
    ]
})
summary

                Metric  Before Cleaning  After Cleaning
0       Number of Rows            96900           96900
1    Number of Columns               19              19
2       Missing Values            67549               0
3       Duplicate Rows                0               0
4    Numerical Columns                4               5
5  Categorical Columns               15              14

In [67]:
dtype_report = pd.DataFrame({
    "Column": df.columns,
    "Before_Data_Type": df_before.dtypes.astype(str).values,
    "After_Data_Type": df.dtypes.astype(str).values
})
dtype_report

                      Column Before_Data_Type After_Data_Type
0                employee_id           object          object
1                  full_name           object          object
2             source_dataset           object          object
3                        age          float64         float64
4                     gender           object          object
5                  ethnicity           object          object
6            education_level           object          object
7           years_experience          float64         float64
8               tenure_years          float64         float64
9                 department           object          object
10                 job_title           object          object
11                   country           object          object
12             remote_status           object          object
13        performance_rating           object          object
14  performance_review_score          float64         float64
15                 hire_date           object          object
16                  currency           object          object
17                salary_raw           object         float64
18                  pay_band           object          object

In [69]:
from google.colab import files
files.download('cleaned_dataset.csv')